timeout: 5
default_entry: 1
graphics: no

/KeshOS NT Workstation 0.8.1 (RAM Boot)
    protocol: multiboot1
    kernel_path: boot():/loader/freeldr.sys
    cmdline: SystemPartition=\ defaultos=LiveImg_RamDisk timeout=0 loader\freeldr.ini

/KeshOS NT Workstation 0.8.1 (Screen Debug)
    protocol: multiboot1
    kernel_path: boot():/loader/freeldr.sys
    cmdline: SystemPartition=\ defaultos=LiveImg_Screen timeout=0 loader\freeldr.ini

/KeshOS NT Setup (Install Mode)
    protocol: multiboot1
    kernel_path: boot():/loader/freeldr.sys
    cmdline: SystemPartition=\ defaultos=Setup timeout=0 loader\freeldr.ini
