.section .rodata
.globl file_icon_bmp_start
.globl file_icon_bmp_end
file_icon_bmp_start:
.incbin "src/gui/apps/file/file_icon.bmp"
file_icon_bmp_end:
.globl music_icon_bmp_start
.globl music_icon_bmp_end
music_icon_bmp_start:
.incbin "src/gui/apps/music/music_icon.bmp"
music_icon_bmp_end:
.globl about_bmp_start
.globl about_bmp_end
about_bmp_start:
.incbin "src/gui/apps/about/about.bmp"
about_bmp_end:
.globl wallpaper_bmp_start
.globl wallpaper_bmp_end
wallpaper_bmp_start:
.incbin "src/gui/wallpaper/wallpaper.bmp"
wallpaper_bmp_end:
.globl cursor_bmp_start
.globl cursor_bmp_end
cursor_bmp_start:
.incbin "src/gui/cursor/cursor.bmp"
cursor_bmp_end:
.globl volume_bmp_start
.globl volume_bmp_end
volume_bmp_start:
.incbin "src/gui/volume.bmp"
volume_bmp_end:
.globl volume_mute_bmp_start
.globl volume_mute_bmp_end
volume_mute_bmp_start:
.incbin "src/gui/volume_mute.bmp"
volume_mute_bmp_end:
.globl volume_min_bmp_start
.globl volume_min_bmp_end
volume_min_bmp_start:
.incbin "src/gui/volume_min.bmp"
volume_min_bmp_end:
.globl volume_max_bmp_start
.globl volume_max_bmp_end
volume_max_bmp_start:
.incbin "src/gui/volume_max.bmp"
volume_max_bmp_end:
.globl calc_icon_bmp_start
.globl calc_icon_bmp_end
calc_icon_bmp_start:
.incbin "src/gui/apps/calc/calc_icon.bmp"
calc_icon_bmp_end:
.globl notes_icon_bmp_start
.globl notes_icon_bmp_end
notes_icon_bmp_start:
.incbin "src/gui/apps/notes/notes_icon.bmp"
notes_icon_bmp_end:
.globl settings_icon_bmp_start
.globl settings_icon_bmp_end
settings_icon_bmp_start:
.incbin "src/gui/apps/settings/settings_icon.bmp"
settings_icon_bmp_end:
.globl terminal_icon_bmp_start
.globl terminal_icon_bmp_end
terminal_icon_bmp_start:
.incbin "src/gui/apps/file/terminal_icon.bmp"
terminal_icon_bmp_end:
.globl wallpaper_day_bmp_start
.globl wallpaper_day_bmp_end
wallpaper_day_bmp_start:
.incbin "src/gui/wallpaper/wallpaper_day.bmp"
wallpaper_day_bmp_end:
.globl wallpaper_night_bmp_start
.globl wallpaper_night_bmp_end
wallpaper_night_bmp_start:
.incbin "src/gui/wallpaper/wallpaper_night.bmp"
wallpaper_night_bmp_end:
.globl doom_icon_bmp_start
.globl doom_icon_bmp_end
doom_icon_bmp_start:
.incbin "src/gui/apps/doom/doom.bmp"
doom_icon_bmp_end:
.globl doom_wad_start
.globl doom_wad_end
doom_wad_start:
.incbin "src/gui/apps/doom/DOOM.WAD"
doom_wad_end:
.globl notepad_elf_start
.globl notepad_elf_end
notepad_elf_start:
.incbin "build/apps/notepad.elf"
notepad_elf_end:
.globl explorer_elf_start
.globl explorer_elf_end
explorer_elf_start:
.incbin "build/apps/explorer.elf"
explorer_elf_end:
.globl notepad_kea_start
.globl notepad_kea_end
notepad_kea_start:
.incbin "build/apps/notepad.kea"
notepad_kea_end:
.globl explorer_kea_start
.globl explorer_kea_end
explorer_kea_start:
.incbin "build/apps/explorer.kea"
explorer_kea_end:
.globl taskmgr_kea_start
.globl taskmgr_kea_end
taskmgr_kea_start:
.incbin "build/apps/taskmgr.kea"
taskmgr_kea_end:
.globl paint_kea_start
.globl paint_kea_end
paint_kea_start:
.incbin "build/apps/paint.kea"
paint_kea_end:
.globl shell_kea_start
.globl shell_kea_end
shell_kea_start:
.incbin "build/apps/shell.kea"
shell_kea_end:
.globl settings_elf_start
.globl settings_elf_end
settings_elf_start:
.incbin "build/apps/settings.elf"
settings_elf_end:
.globl settings_kea_start
.globl settings_kea_end
settings_kea_start:
.incbin "build/apps/settings.kea"
settings_kea_end:
.globl about_elf_start
.globl about_elf_end
about_elf_start:
.incbin "build/apps/about.elf"
about_elf_end:
.globl about_kea_start
.globl about_kea_end
about_kea_start:
.incbin "build/apps/about.kea"
about_kea_end:
.globl browser_kea_start
.globl browser_kea_end
browser_kea_start:
.incbin "build/apps/browser.kea"
browser_kea_end:
.globl installer_kea_start
.globl installer_kea_end
installer_kea_start:
.incbin "build/apps/installer.kea"
installer_kea_end:
.globl kesh_icon_settings_start
.globl kesh_icon_settings_end
kesh_icon_settings_start:
.incbin "assets/icons/settings.ico"
kesh_icon_settings_end:
.globl kesh_icon_picture_start
.globl kesh_icon_picture_end
kesh_icon_picture_start:
.incbin "assets/icons/picture.ico"
kesh_icon_picture_end:
.globl kesh_icon_file_start
.globl kesh_icon_file_end
kesh_icon_file_start:
.incbin "assets/icons/file.ico"
kesh_icon_file_end:
.globl kesh_icon_folder_start
.globl kesh_icon_folder_end
kesh_icon_folder_start:
.incbin "assets/icons/folder.ico"
kesh_icon_folder_end:
.globl kesh_icon_explorer_start
.globl kesh_icon_explorer_end
kesh_icon_explorer_start:
.incbin "assets/icons/explorer.ico"
kesh_icon_explorer_end:
.globl kesh_icon_terminal_start
.globl kesh_icon_terminal_end
kesh_icon_terminal_start:
.incbin "assets/icons/terminal.ico"
kesh_icon_terminal_end:
.globl kesh_icon_taskmgr_start
.globl kesh_icon_taskmgr_end
kesh_icon_taskmgr_start:
.incbin "assets/icons/taskmgr.ico"
kesh_icon_taskmgr_end:
.globl kesh_icon_browser_start
.globl kesh_icon_browser_end
kesh_icon_browser_start:
.incbin "assets/icons/browser.ico"
kesh_icon_browser_end:
.globl kesh_icon_installer_start
.globl kesh_icon_installer_end
kesh_icon_installer_start:
.incbin "assets/icons/installer.ico"
kesh_icon_installer_end:
.globl kesh_icon_notepad_start
.globl kesh_icon_notepad_end
kesh_icon_notepad_start:
.incbin "assets/icons/notepad.ico"
kesh_icon_notepad_end:
.globl kesh_icon_paint_start
.globl kesh_icon_paint_end
kesh_icon_paint_start:
.incbin "assets/icons/paint.ico"
kesh_icon_paint_end:
.globl kesh_icon_doom_start
.globl kesh_icon_doom_end
kesh_icon_doom_start:
.incbin "assets/icons/doom.ico"
kesh_icon_doom_end:
