set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR x86_64)
set(CMAKE_SYSROOT "/home/danila/Рабочий стол/keshos/toolchain/musl")
set(CMAKE_C_COMPILER clang)
set(CMAKE_CXX_COMPILER clang++)
set(CMAKE_ASM_COMPILER clang)
set(CMAKE_C_COMPILER_TARGET x86_64-unknown-linux-musl)
set(CMAKE_CXX_COMPILER_TARGET x86_64-unknown-linux-musl)
set(CMAKE_ASM_COMPILER_TARGET x86_64-unknown-linux-musl)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
set(CMAKE_C_FLAGS_INIT "--rtlib=compiler-rt")
set(CMAKE_CXX_FLAGS_INIT "--rtlib=compiler-rt --unwindlib=libunwind -stdlib=libc++ -isystem \"/home/danila/Рабочий стол/keshos/toolchain/musl/include/c++/v1\"")
set(CMAKE_EXE_LINKER_FLAGS_INIT "-static --rtlib=compiler-rt -fuse-ld=lld")
set(CMAKE_SHARED_LINKER_FLAGS_INIT "--rtlib=compiler-rt -fuse-ld=lld")
set(CMAKE_CXX_STANDARD_LIBRARIES_INIT "-lc++abi -lunwind -lc")
set(CMAKE_FIND_ROOT_PATH "/home/danila/Рабочий стол/keshos/toolchain/musl")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
