[FREELOADER]
DefaultOS=LiveImg_RamDisk
TimeOut=5

[Display]
TitleText=KeshOS Boot Media
MinimalUI=No

[Operating Systems]
LiveImg_RamDisk="KeshOS Live (RAM Boot)"
LiveImg_Screen="KeshOS Live (Screen Debug)"
Setup="Install KeshOS (Setup Mode)"

[LiveImg_RamDisk]
BootType=Windows2003
SystemPath=ramdisk(0)\reactos
Options=/DEBUG /DEBUGPORT=COM1 /SOS /FASTDETECT /MININT /NOEXECUTE=ALWAYSOFF /NUMPROC=1 /RDPATH= /RDEXPORTASCD

[LiveImg_Screen]
BootType=Windows2003
SystemPath=ramdisk(0)\reactos
Options=/DEBUG /DEBUGPORT=SCREEN /SOS /FASTDETECT /MININT /NOEXECUTE=ALWAYSOFF /NUMPROC=1 /RDPATH= /RDEXPORTASCD

[Setup]
BootType=ReactOSSetup
Options=/DEBUG /DEBUGPORT=COM1 /SOS /FASTDETECT /NOEXECUTE=ALWAYSOFF /NUMPROC=1

;[LiveImg_LogFile]
;BootType=Windows2003
;SystemPath=\reactos
;Options=/DEBUG /DEBUGPORT=FILE:\Device\HarddiskX\PartitionY\debug.log /SOS /FASTDETECT /MININT
